# OpenAI
MODEL = "gpt-4o-mini"
TEMPERATURE = 0
SEED = 42
EMBEDDING_MODEL = "text-embedding-3-small"
MAX_RETRIES = 6

# Retrieval
QUESTION_FETCH_K = 10
QUESTION_RESULT_K = 2
QUESTION_MIN_THRESHOLD = 0.0
QUESTION_MAX_THRESHOLD = 0.3

# Data loader
LOADER_BATCH_SIZE = 100
LOADER_MAX_RETRIES = 5
